import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar1 } from "@/components/ui/navbar-1";

const font = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: "Scale Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={font.className}
      >
        <Navbar1/>
        {children}
      </body>
    </html>
  );
}
